services:

    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    ToolboxBundle\Resolver\ContextResolverInterface: '@ToolboxBundle\Resolver\ContextResolver'
    ToolboxBundle\Resolver\ContextResolver: ~