services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ToolboxBundle\Builder\BrickConfigBuilderInterface: '@ToolboxBundle\Builder\BrickConfigBuilder'
    ToolboxBundle\Builder\BrickConfigBuilder: ~

    ToolboxBundle\Builder\InlineConfigBuilderInterface: '@ToolboxBundle\Builder\InlineConfigBuilder'
    ToolboxBundle\Builder\InlineConfigBuilder:
        calls:
            - [ setHeadlessEditableRenderer, [ '@ToolboxBundle\Document\Editable\HeadlessEditableRenderer' ] ]
            - [ setHeadlessEditableInfoFactory, [ '@ToolboxBundle\Factory\HeadlessEditableInfoFactory' ] ]

    ToolboxBundle\Document\Editable\EditableWorker:
        public: true

    ToolboxBundle\Document\Editable\ConfigParser: ~
    ToolboxBundle\Document\Editable\HeadlessEditableRenderer: ~

    ToolboxBundle\Factory\HeadlessEditableInfoFactory: ~

