services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ToolboxBundle\Builder\BrickConfigBuilderInterface: '@ToolboxBundle\Builder\BrickConfigBuilder'
    ToolboxBundle\Builder\BrickConfigBuilder: ~

    ToolboxBundle\Builder\InlineConfigBuilderInterface: '@ToolboxBundle\Builder\InlineConfigBuilder'
    ToolboxBundle\Builder\InlineConfigBuilder:
        calls:
            - [ setEditableWorker, [ '@ToolboxBundle\Document\Editable\EditableWorker' ] ]

    ToolboxBundle\Document\Editable\EditableJsonFetcher: ~

    ToolboxBundle\Document\Editable\EditableWorker:
        public: true
