services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ToolboxBundle\EventListener\Admin\AssetListener:
        arguments:
            $enabledWysiwygEditorName: '%toolbox.wysiwyg_editor%'
        tags:
            - { name: kernel.event_subscriber }

    ToolboxBundle\EventListener\Admin\EditmodeListener:
        tags:
            - { name: kernel.event_subscriber }

    ToolboxBundle\EventListener\Frontend\FrontendJsListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }