services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ToolboxBundle\Normalizer\DownloadRelationsNormalizer:
        tags:
            - { name: toolbox.property.normalizer }

    ToolboxBundle\Normalizer\GalleryRelationsNormalizer:
        tags:
            - { name: toolbox.property.normalizer }

    ToolboxBundle\Normalizer\ImageEditableNormalizer:
        tags:
            - { name: toolbox.property.normalizer }

    ToolboxBundle\Normalizer\LinkNormalizer:
        tags:
            - { name: toolbox.property.normalizer }

    ToolboxBundle\Normalizer\ThumbnailNormalizer:
        tags:
            - { name: toolbox.property.normalizer }