services:
    ToolboxBundle\Document\ToolboxAreabrick\Snippet\Snippet:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: snippet }