services:
    ToolboxBundle\Document\Areabrick\Accordion\Accordion:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: accordion }
toolbox:
    areas:
        accordion:
            config_parameter:
                reload_on_close: true
            config_elements:
                type:
                    type: select
                    title: 'Type'
                    config:
                        store:
                            panel-default: 'Default'
                            panel-danger: 'Dangers'
                        default: panel-default
                component:
                    type: select
                    title: 'Component'
                    description: ~
                    col_class: ~
                    config:
                        store:
                            accordion: 'Accordion'
                            tab: 'Tab'
                        default: accordion
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~