services:
    ToolboxBundle\Document\Areabrick\Download\Download:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        autowire: true
        tags:
            - { name: pimcore.area.brick, id: download }
toolbox:
    areas:
        download:
            config_elements:
                downloads:
                    type: relations
                    title: 'Files'
                    config:
                        reload: true
                show_preview_images:
                    type: checkbox
                    title: 'Show preview images'
                    config:
                        reload: false
                show_file_info:
                    type: checkbox
                    title: 'Show file info'
                    config:
                        reload: false
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            config_parameter: ~