services:
    ToolboxBundle\Document\Areabrick\Gallery\Gallery:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: gallery }
toolbox:
    areas:
        gallery:
            config_elements:
                images:
                    type: relations
                    title: 'Images or Folder'
                    config:
                        reload: true
                use_light_box:
                    type: checkbox
                    title: 'Use Lightbox'
                    config:
                        reload: false
                use_thumbnails:
                    type: checkbox
                    title: 'Use Thumbnails'
                    config:
                        reload: false
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~