toolbox:
    areas:
        parallaxContainerSection:
            config_elements:
                template:
                    type: select
                    title: 'Section Template'
                    config:
                        reload: true
                        store:
                            no-template: 'No Template'
                        default: no-template
                container_type:
                    type: select
                    title: 'Section Wrapper Type'
                    config:
                        reload: true
                        description: 'If you need to add some content columns, apply a default or fluid container as wrapper.'
                        store:
                            none: 'No Section Wrapper'
                            container: 'Default Container Wrapper'
                            container-fluid: 'Fluid Container Wrapper'
                        default: none
                background_image:
                    type: relation
                    title: 'Background Image'
                    config:
                        reload: true
                        types:
                          - asset
                        subtypes:
                            asset:
                              - image
                              - video
                background_color:
                    type: select
                    title: 'Background Color'
                    config:
                        reload: true
                        store:
                            no-background-color: 'No Background Color'
                        default: no-background-color
            config_parameter:
                background_image_mode: data
                background_color_mode: data