services:
    ToolboxBundle\Document\Areabrick\ParallaxContainer\ParallaxContainer:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: parallaxContainer }
toolbox:
    areas:
        parallaxContainer:
            config_elements:
                template:
                    type: select
                    title: 'Parallax Template'
                    config:
                        reload: true
                        store:
                            no-template: 'No Template'
                        default: no-template
                background_image:
                    type: relation
                    title: 'Background Image'
                    config:
                        types:
                          - asset
                        subtypes:
                            asset:
                              - image
                              - video
                        reload: true
                background_color:
                    type: select
                    title: Background Color
                    config:
                        reload: true
                        store:
                            no-background-color: 'No Background Color'
                        default: no-background-color
                image_front:
                    type: parallaximage
                    title: 'Images In Front Of Main Container'
                    config:
                        position:
                            top-left: 'Top Left'
                            top-center: 'Top Center'
                            top-right: 'Top Right'
                            bottom-left: 'Bottom Left'
                            bottom-center: 'Bottom Center'
                            bottom-right: 'Bottom Right'
                            center-left: 'Center Left'
                            center-center: 'Center Center'
                            center-right: 'Center Right'
                        size:
                            half-window-width: 'Half Window Width'
                            third-window-width: 'Third Window Width'
                            quarter-window-width: 'Quarter Window Width'
                        reload: true
                image_behind:
                    type: parallaximage
                    title: 'Images Behind Main Container'
                    config:
                        position:
                            top-left: 'Top Left'
                            top-center: 'Top Center'
                            top-right: 'Top Right'
                            bottom-left: 'Bottom Left'
                            bottom-center: 'Bottom Center'
                            bottom-right: 'Bottom Right'
                            center-left: 'Center Left'
                            center-center: 'Center Center'
                            center-right: 'Center Right'
                        size:
                            half-window-width: 'Half Window Width'
                            third-window-width: 'Third Window Width'
                            quarter-window-width: 'Quarter Window Width'
                        reload: true
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            config_parameter:
                window_size: large
                background_mode: wrap
                background_image_mode: data
                background_color_mode: data