services:
    ToolboxBundle\Document\Areabrick\Spacer\Spacer:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: spacer }
toolbox:
    areas:
        spacer:
            config_elements:
                spacer_class:
                    type: select
                    title: 'Space Class'
                    config:
                        store:
                            spacer-none: 'No Space'
                            spacer-50: '50 Pixel'
                        default: spacer-none
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~