services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ToolboxBundle\Calculator\ColumnCalculatorInterface: '@ToolboxBundle\Calculator\Bootstrap4\ColumnCalculator'
    ToolboxBundle\Calculator\SlideColumnCalculatorInterface: '@ToolboxBundle\Calculator\Bootstrap4\SlideColumnCalculator'

    # column calculator
    ToolboxBundle\Calculator\Bootstrap3\ColumnCalculator:
        calls:
            - [setConfigManager, ['@ToolboxBundle\Manager\ConfigManager']]
        tags:
            - { name: toolbox.calculator, type: column }

    ToolboxBundle\Calculator\Bootstrap4\ColumnCalculator:
        calls:
            - [setConfigManager, ['@ToolboxBundle\Manager\ConfigManager']]
        tags:
            - { name: toolbox.calculator, type: column }

    ToolboxBundle\Calculator\UIkit3\ColumnCalculator:
        calls:
            - [setConfigManager, ['@ToolboxBundle\Manager\ConfigManager']]
        tags:
            - { name: toolbox.calculator, type: column }

    # slide column calculator
    ToolboxBundle\Calculator\Bootstrap3\SlideColumnCalculator:
        tags:
            - { name: toolbox.calculator, type: slide_column }

    ToolboxBundle\Calculator\Bootstrap4\SlideColumnCalculator:
        tags:
            - { name: toolbox.calculator, type: slide_column }

    ToolboxBundle\Calculator\UIkit3\SlideColumnCalculator:
        tags:
            - { name: toolbox.calculator, type: slide_column }