services:

    ToolboxBundle\Controller\Admin\ColumnAdjusterController:
        public: true
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: controller.service_arguments }

    ToolboxBundle\Controller\Admin\SettingsController:
        public: true
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
              - { name: controller.service_arguments }

    ToolboxBundle\Controller\AjaxController:
        public: true
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
              - { name: controller.service_arguments }

    ToolboxBundle\Controller\SnippetController:
        public: true
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        tags:
              - { name: controller.service_arguments }
