services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ToolboxBundle\EventListener\Frontend\FrontendJsListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }