services:

    # twig extensions
    ToolboxBundle\Twig\Extension\AreaBlockConfigExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DownloadExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DocumentEditableExtension:
        parent: Pimcore\Twig\Extension\DocumentEditableExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DataAttributesExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\LayoutExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\ImageThumbnailExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\CkEditorExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\GoogleAPIKeysExtension:
        arguments:
            $fallbackBrowserKey: '%toolbox.google_maps.browser_api_key%'
        public: false
        autowire: true
        tags:
            - { name: twig.extension }
