#!/usr/bin/env bash

export DACHCOM_BUNDLE_HOME=$TRAVIS_BUILD_DIR
export DACHCOM_BUNDLE_NAME="Toolbox"
export DACHCOM_BUNDLE_REPO_NAME="toolbox"
export DACHCOM_BUNDLE_COMMIT=$TRAVIS_COMMIT
export DACHCOM_BUNDLE_BRANCH=$TRAVIS_BRANCH

export DACHCOM_BUNDLE_CLASS='ToolboxBundle\ToolboxBundle'
export DACHCOM_BUNDLE_INSTALLER_CLASS='ToolboxBundle\Tool\Install'

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 # system files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/extensions.template.php"]="var/config/extensions.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/system.template.php"]="var/config/system.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/appKernel"]="app/AppKernel.php"
 # template files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/controller/DefaultController"]="src/AppBundle/Controller/DefaultController.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/default"]="app/Resources/views/Default/default.html.twig"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/snippet"]="app/Resources/views/Default/snippet.html.twig"
)