#!/bin/bash

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 # system files
 ["./tests/_etc/config/bundle/extensions.php.template"]="./var/config/extensions.php"
 ["./tests/_etc/config/bundle/debug.php.template"]="./var/config/debug-mode.php"
 ["./tests/_etc/config/bundle/system.yml.template"]="./var/config/system.yml"
 # template files
 ["./tests/_etc/config/bundle/template/controller/DefaultController"]="./src/AppBundle/Controller/DefaultController.php"
 ["./tests/_etc/config/bundle/template/views/default"]="./app/Resources/views/Default/default.html.twig"
 ["./tests/_etc/config/bundle/template/views/snippet"]="./app/Resources/views/Default/snippet.html.twig"
)