#!/usr/bin/env bash
set -e

export DACHCOM_BUNDLE_HOME=$TRAVIS_BUILD_DIR
export DACHCOM_BUNDLE_NAME="Toolbox"
export DACHCOM_BUNDLE_REPO_NAME="pimcore-toolbox"
export DACHCOM_BUNDLE_COMMIT=$TRAVIS_COMMIT
export DACHCOM_BUNDLE_BRANCH=$TRAVIS_BRANCH

$TRAVIS_BUILD_DIR/tests/etc/travis/setup/tests/install