pimcore:
    documents:
        editables:
            map:
                googlemap: \ToolboxBundle\Model\Document\Editable\GoogleMap
                parallaximage: \ToolboxBundle\Model\Document\Editable\ParallaxImage
                vhs: \ToolboxBundle\Model\Document\Editable\Vhs
                columnadjuster: \ToolboxBundle\Model\Document\Editable\ColumnAdjuster