toolbox:
    areas:
        anchor:
            config_elements:
                anchor_name:
                    type: input
                    title: 'Anchor Name'
                    config: ~
                anchor_title:
                    type: input
                    title: 'Anchor Title'
                    config: ~