services:
    ToolboxBundle\Document\ToolboxAreabrick\Anchor\Anchor:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: anchor }