toolbox:
    areas:
        content:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            inline_config_elements:
                wysiwyg:
                    type: wysiwyg