services:
    ToolboxBundle\Document\ToolboxAreabrick\Container\Container:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: container }