services:
    ToolboxBundle\Document\ToolboxAreabrick\Content\Content:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: content }