services:
    ToolboxBundle\Document\ToolboxAreabrick\Download\Download:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        autowire: true
        tags:
            - { name: toolbox.area.brick, id: download }
