toolbox:
    areas:
        download:
            config_elements:
                downloads:
                    type: relations
                    title: 'Files'
                    config: ~
                show_preview_images:
                    type: checkbox
                    title: 'Show preview images'
                    config: ~
                show_file_info:
                    type: checkbox
                    title: 'Show file info'
                    config: ~
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            config_parameter: ~
            inline_config_elements:
                downloads: '<'
            additional_property_normalizer:
                downloads: ToolboxBundle\Normalizer\DownloadRelationsNormalizer
