services:
    ToolboxBundle\Document\ToolboxAreabrick\Headline\Headline:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: headline }
