toolbox:
    areas:
        headline:
            config_elements:
                headline_type:
                    type: select
                    title: 'Headline Size'
                    config:
                        name: headlineType
                        store:
                            h1: Headline 1
                            h2: Headline 2
                            h3: Headline 3
                            h4: Headline 4
                            h5: Headline 5
                            h6: Headline 6
                        default: h3
                anchor_name:
                    type: input
                    title: 'Anchor Name'
                    config: ~
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            inline_config_elements:
                headline_text:
                    type: input
                    title: 'Text'
                headline_type: '<'
