toolbox:
    areas:
        iFrame:
            config_elements:
                url:
                    type: input
                    title: 'iFrame Url'
                iheight:
                    type: numeric
                    title: 'Initial Height'
                    config:
                        default: 200
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~