services:
    ToolboxBundle\Document\ToolboxAreabrick\IFrame\IFrame:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: iFrame }
