services:
    ToolboxBundle\Document\ToolboxAreabrick\Image\Image:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: image }
