toolbox:
    areas:
        linkList:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~

            inline_config_elements:
                linklistblock:
                    type: block
                    children:
                        linklist:
                            type: link
                            property_normalizer: ToolboxBundle\Normalizer\LinkNormalizer
                            title: 'Link'
                            config:
                                class: 'list-link'