services:
    ToolboxBundle\Document\ToolboxAreabrick\LinkList\LinkList:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: linkList }
