services:
    ToolboxBundle\Document\ToolboxAreabrick\ParallaxContainer\ParallaxContainer:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        arguments:
            - '@Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator'
            - '@pimcore.templating.engine.delegating'
        tags:
            - { name: toolbox.area.brick, id: parallaxContainer }
