toolbox:
    areas:
        separator:
            config_elements:
                space:
                    type: select
                    title: 'Space before & after separator'
                    config:
                        store:
                            default: 'Default'
                            medium: 'Medium'
                            large: 'Large'
                        default: default
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~

            inline_config_elements:
                space: '<'
