services:
    ToolboxBundle\Document\ToolboxAreabrick\Spacer\Spacer:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: spacer }
