services:
    ToolboxBundle\Document\ToolboxAreabrick\Teaser\Teaser:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: teaser }
