services:
    ToolboxBundle\Document\ToolboxAreabrick\Video\Video:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: toolbox.area.brick, id: video }
