toolbox:
    areas_appearance:
        accordion:
            disallowed:
                - accordion
                - container
                - slideColumns
                - parallaxContainer
        columns:
            disallowed:
                - container
                - parallaxContainer
        slideColumns:
            disallowed:
                - slideColumns
                - accordion
                - container
                - parallaxContainer
                - columns
                - anchor
        container:
            disallowed:
                - container
                - parallaxContainer
        parallaxContainer:
            disallowed:
                - container
                - parallaxContainer

    snippet_areas_appearance:
        accordion:
            disallowed:
                - accordion
                - container
                - slideColumns
                - parallaxContainer
        columns:
            disallowed:
                - container
                - parallaxContainer
        slideColumns:
            disallowed:
                - slideColumns
                - accordion
                - container
                - parallaxContainer
                - columns
                - anchor
        container:
            disallowed:
                - container
                - parallaxContainer
        parallaxContainer:
            disallowed:
                - container
                - parallaxContainer