doctrine_migrations:
    migrations_paths:
        'ToolboxBundle\Migrations': '@ToolboxBundle/Migrations'

imports:
    - { resource: areas/*.yml }
    - { resource: ckeditor/*.yml }
    - { resource: registry.yml }
    - { resource: theme.yml }
    - { resource: area_restrictions.yml }
    - { resource: data_attributes.yml }
    - { resource: image_thumbnails.yml }
    - { resource: toolbar.yml }
    - { resource: document/editables.yml }