services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # registry: language
    ToolboxBundle\Registry\CalculatorRegistryInterface: '@ToolboxBundle\Registry\CalculatorRegistry'
    ToolboxBundle\Registry\CalculatorRegistry:
        arguments:
            $columnInterface: 'ToolboxBundle\Calculator\ColumnCalculatorInterface'
            $slideColumnInterface: 'ToolboxBundle\Calculator\SlideColumnCalculatorInterface'

    # registry: store provider
    ToolboxBundle\Registry\StoreProviderRegistryInterface: '@ToolboxBundle\Registry\StoreProviderRegistry'
    ToolboxBundle\Registry\StoreProviderRegistry: ~
