name: Codeception
on:
    push:
        branches: [ 'master' ]
    pull_request:
        branches: [ 'master' ]

jobs:
    codeception:
        runs-on: ubuntu-latest
        env:
            CHROME_DRIVER_VERSION: 2.41
            SELENIUM_VERSION: 3.6.0
            WEBDRIVER_HOST: localhost
            WEBDRIVER_URL: "http://localhost:8080/"
            DACHCOM_BUNDLE_TEST_DIR: "${{ github.workspace }}/tests"
            DACHCOM_BUNDLE_NAME: "ToolboxBundle"
            DACHCOM_BUNDLE_CLASS: "ToolboxBundle\\ToolboxBundle"
            DACHCOM_BUNDLE_INSTALLER_CLASS: "ToolboxBundle\\Tool\\Install"

            PIMCORE_ENVIRONMENT: "test"
            PIMCORE_TEST_DB_DSN: "mysql://root:root@localhost/dachcom_bundle_test"
            PIMCORE_TEST_URL: "http://localhost"

            SYMFONY_DEPRECATIONS_HELPER: "weak"
            PIMCORE_PHP_ERROR_REPORTING: 32767

            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dachcom_bundle_test
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: dachcom_bundle_test
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            matrix:
                php: [7.4]
                symfony: [^4.4]
                pimcore: [^6.0, ^6.1, ^6.2, ^6.3, ^6.5, ^6.6, ^6.7, ^6.8]
                include:
                    -   pimcore: ^6.0
                        template_tag: v2.0.0
                    -   pimcore: ^6.1
                        template_tag: v2.1.0
                    -   pimcore: ^6.2
                        template_tag: v2.2.0
                    -   pimcore: ^6.3
                        template_tag: v2.3.0
                    -   pimcore: ^6.5
                        template_tag: v2.5.0
                    -   pimcore: ^6.6
                        template_tag: v2.6.0
                    -   pimcore: ^6.7
                        template_tag: v2.7.0
                    -   pimcore: ^6.8
                        template_tag: v2.8.0
                    -   pimcore: ^6.8
                        symfony: ^3.4
                        php: 7.4
                        template_tag: v2.8.0
        steps:
            -   uses: actions/checkout@v2

            -   name: Adjust Error Reporting Level
                if: ${{ matrix.pimcore == '^6.5' }}
                run: |
                    echo "PIMCORE_PHP_ERROR_REPORTING=30711" >> $GITHUB_ENV

            -   name: Generate Application Structure
                run: |
                    git clone -b ${{ matrix.template_tag }} --single-branch --depth 1 https://github.com/pimcore/skeleton.git
                    mv skeleton/app .
                    mv skeleton/bin .
                    mv skeleton/var .
                    mv skeleton/web .
                    mv skeleton/src/AppBundle src

            -   name: Setup Bundle
                env:
                    MATRIX_PIMCORE_VERSION: ${{ matrix.pimcore }}
                    MATRIX_PIMCORE_TEMPLATE_TAG: ${{ matrix.template_tag }}
                run: |
                    chmod +x tests/_etc/scripts/install
                    ./tests/_etc/scripts/install

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: intl
                    coverage: none

            -   name: Check PHP Version
                run: php -v

            -   name: Start MySql Service
                run: |
                    sudo /etc/init.d/mysql start

            -   name: Verify MySql Connection
                run: |
                    sudo apt-get update
                    sudo apt-get install -y mysql-client-5.7
                    mysql -uroot -h127.0.0.1 -proot -e "SHOW DATABASES"

            -   name: Setup MySql
                run: |
                    mysql -uroot -h127.0.0.1 -proot -e "SET GLOBAL innodb_file_format=Barracuda;"
                    mysql -uroot -h127.0.0.1 -proot -e "SET GLOBAL innodb_large_prefix=1;"
                    mysql -uroot -h127.0.0.1 -proot -e "CREATE DATABASE dachcom_bundle_test CHARSET=utf8mb4;"

            -   name: Setup Chromium
                run: |
                    nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &

            -   name: Start Webserver and Chrome
                run: |
                    wget https://get.symfony.com/cli/installer -O - | bash
                    ~/.symfony/bin/symfony server:start --port=8080 --dir=web --force-php-discovery --allow-http --no-tls --daemon

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer Downloads
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Composer install
                run: |
                    composer req pimcore/pimcore:${{ matrix.pimcore }} symfony/symfony:${{ matrix.symfony }} --no-interaction --ignore-platform-reqs --no-scripts
                    composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs

            -   name: Assets Install
                run: |
                    bin/console assets:install web --relative --symlink

            -   name: Tests
                run: |
                    bin/console cache:warmup --env=test
                    vendor/bin/codecept run --env github -c ${{ env.GITHUB_WORKSPACE }}
